---
- name: INSTALL AND CONFIGURE MAAS
  hosts: localhost
  connection: local
  become: yes



  tasks:

    - name: UPDATE SYSTEM
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 8640

    - name:  REMOVING OLD VERSIONS
      shell: yes 'yes' | apt-get purge maas ; sudo apt-get autoremove
